"""Golden slicer profiles and the pre-print safety check."""

from __future__ import annotations

import pytest

from app.doctor.engine import DiagnosticInput, DiagnosticsEngine
from app.gcode.validator import analyse_gcode
from app.klipper.model import parse_config
from app.klipper.validator import NEPTUNE_3_PLUS
from app.preflight import run_preflight
from app.slicer.golden import GoldenProfileStore

CFG_TEXT = """
[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
[stepper_x]
position_min: 0
position_max: 330
[stepper_y]
position_min: 0
position_max: 330
[stepper_z]
position_min: 0
position_max: 410
[probe]
z_offset: 2.1
[safe_z_home]
home_xy_position: 160, 160
[bed_mesh]
mesh_min: 30, 30
#*# <---------------------- SAVE_CONFIG
#*# [probe]
#*# z_offset = 2.100
#*# [bed_mesh default]
#*# version = 1
"""
CONFIG = parse_config(CFG_TEXT)

GOOD_GCODE = """; generated by PrusaSlicer 2.8.1+linux
; nozzle_diameter = 0.4
; print_settings_id = Neptune3Plus 0.20 Standard
G90
M83
M104 S210
M140 S60
G28
G1 X10 Y10 Z0.2 F1800
G1 X300 Y300 E5 F3000
"""


# --------------------------------------------------------------------------- #
# Golden profile registry
# --------------------------------------------------------------------------- #


@pytest.fixture()
def profiles(tmp_path):
    from app.db import Database

    db = Database(tmp_path / "profiles.db")
    yield GoldenProfileStore(db)
    db.close()


def test_saving_the_same_name_creates_a_new_version(profiles):
    first = profiles.save("Neptune3Plus 0.20", {"layer_height": 0.2})
    second = profiles.save("Neptune3Plus 0.20", {"layer_height": 0.24})
    assert first.version == 1
    assert second.version == 2
    assert second.parent_id == first.id


def test_saving_identical_settings_does_not_create_a_version(profiles):
    first = profiles.save("P", {"layer_height": 0.2})
    again = profiles.save("P", {"layer_height": 0.2})
    assert again.id == first.id
    assert len(profiles.versions_of("P")) == 1


def test_editing_a_golden_profile_never_overwrites_it(profiles):
    """The whole point of pinning: convenience must not touch the known-good one."""
    original = profiles.save("Golden N3P", {"layer_height": 0.2, "accel": 3000})
    profiles.mark_golden(original.id)

    edited = profiles.save("Golden N3P", {"layer_height": 0.2, "accel": 6000})

    assert edited.id != original.id
    assert edited.golden is False
    stored = profiles.get(original.id)
    assert stored.golden is True
    assert stored.settings["accel"] == 3000      # untouched


def test_a_golden_profile_cannot_be_deleted(profiles):
    profile = profiles.save("P", {"a": 1})
    profiles.mark_golden(profile.id)
    assert profiles.delete(profile.id) is False
    assert profiles.get(profile.id) is not None


def test_a_candidate_profile_can_be_deleted(profiles):
    profile = profiles.save("P", {"a": 1})
    assert profiles.delete(profile.id) is True


def test_promoting_a_new_version_demotes_the_previous_golden_for_that_name(profiles):
    first = profiles.save("P", {"a": 1})
    profiles.mark_golden(first.id)
    second = profiles.save("P", {"a": 2})
    profiles.mark_golden(second.id)
    assert profiles.get(first.id).golden is False
    assert profiles.get(second.id).golden is True


def test_golden_is_per_profile_name_not_global(profiles):
    a = profiles.save("Draft", {"a": 1})
    b = profiles.save("Fine", {"b": 1})
    profiles.mark_golden(a.id)
    profiles.mark_golden(b.id)
    assert {p.name for p in profiles.golden_profiles()} == {"Draft", "Fine"}


def test_print_outcomes_are_recorded(profiles):
    profile = profiles.save("P", {"a": 1})
    profiles.record_print(profile.id, success=True)
    profiles.record_print(profile.id, success=False)
    updated = profiles.get(profile.id)
    assert updated.successful_prints == 1
    assert updated.failed_prints == 1


def test_golden_names_feed_the_gcode_validator(profiles):
    profile = profiles.save("Neptune3Plus 0.20 Standard", {"a": 1})
    profiles.mark_golden(profile.id)
    report = analyse_gcode(GOOD_GCODE, config=CONFIG, golden_profiles=profiles.golden_names())
    assert report.verified_profile is True
    assert report.profile_status == "golden"


# --------------------------------------------------------------------------- #
# Preflight
# --------------------------------------------------------------------------- #


def healthy_report():
    return DiagnosticsEngine(profile=NEPTUNE_3_PLUS).run(
        DiagnosticInput(
            moonraker_reachable=True,
            klippy_state="ready",
            config=CONFIG,
            homed_axes="xyz",
            probe_triggered=False,
            mcu_awake=True,
            heaters={"extruder": {"temperature": 24.0, "target": 0.0}},
            disk_free_gb=30.0,
        )
    )


def test_a_healthy_printer_with_clean_gcode_is_ready():
    gcode = analyse_gcode(
        GOOD_GCODE, config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"]
    )
    report = run_preflight(health=healthy_report(), gcode=gcode)
    assert report.verdict == "ready"
    assert report.ready is True


def test_a_gcode_error_blocks_the_print():
    gcode = analyse_gcode(
        GOOD_GCODE + "G1 X500 Y10\n", config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"]
    )
    report = run_preflight(health=healthy_report(), gcode=gcode)
    assert report.verdict == "blocked"
    assert any(c.id.startswith("gcode_outside_build_volume") for c in report.failures)


def test_a_critical_printer_finding_blocks_the_print():
    health = DiagnosticsEngine(profile=NEPTUNE_3_PLUS).run(
        DiagnosticInput(
            moonraker_reachable=True,
            klippy_state="ready",
            config=CONFIG,
            probe_triggered=True,
            mcu_awake=True,
        )
    )
    gcode = analyse_gcode(GOOD_GCODE, config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"])
    report = run_preflight(health=health, gcode=gcode)
    assert report.verdict == "blocked"


def test_strict_mode_turns_warnings_into_blocks():
    gcode = analyse_gcode(GOOD_GCODE + "M413 S1\n", config=CONFIG, golden_profiles=[])
    lenient = run_preflight(health=healthy_report(), gcode=gcode, strict=False)
    strict = run_preflight(health=healthy_report(), gcode=gcode, strict=True)
    assert lenient.verdict == "warning"
    assert strict.verdict == "blocked"


def test_a_missing_gcode_analysis_is_an_error_not_a_pass():
    report = run_preflight(health=healthy_report(), gcode=None)
    assert report.verdict == "blocked"
    assert any(c.id == "gcode_validation" for c in report.failures)


def test_an_unchecked_printer_warns_rather_than_passing():
    gcode = analyse_gcode(GOOD_GCODE, config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"])
    report = run_preflight(health=None, gcode=gcode)
    assert report.verdict == "warning"


def test_the_banner_reports_every_field_from_the_brief():
    gcode = analyse_gcode(GOOD_GCODE, config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"])
    banner = run_preflight(health=healthy_report(), gcode=gcode).banner
    assert banner["slicer"] == "PrusaSlicer"
    assert banner["printer_profile"] == "Neptune3Plus 0.20 Standard"
    assert banner["profile_status"] == "GOLDEN"
    assert banner["gcode_validation"] == "SAFE"
    assert banner["build_volume"] == "PASSED"
    assert banner["unsupported_commands"] == "NONE"
    assert banner["motion_limits"] == "PASSED"


def test_the_banner_names_the_unsupported_commands_it_found():
    gcode = analyse_gcode(GOOD_GCODE + "M413 S1\n", config=CONFIG, golden_profiles=[])
    banner = run_preflight(health=healthy_report(), gcode=gcode).banner
    assert "M413" in banner["unsupported_commands"]


def test_unverified_gcode_is_surfaced_in_the_banner():
    cura = GOOD_GCODE.replace("; generated by PrusaSlicer 2.8.1+linux", ";Generated with Cura_SteamEngine 5.6")
    gcode = analyse_gcode(cura, config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"])
    report = run_preflight(health=healthy_report(), gcode=gcode)
    assert report.banner["profile_status"] == "UNVERIFIED"
    assert report.verdict == "warning"


def test_a_filament_shortage_warns_without_blocking():
    gcode = analyse_gcode(GOOD_GCODE, config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"])
    report = run_preflight(
        health=healthy_report(), gcode=gcode,
        filament_ok=False, filament_message="Only 12 g left",
    )
    assert report.verdict == "warning"
    assert any(c.id == "filament" for c in report.warnings)


def test_the_report_serialises_for_the_api():
    gcode = analyse_gcode(GOOD_GCODE, config=CONFIG, golden_profiles=["Neptune3Plus 0.20 Standard"])
    payload = run_preflight(health=healthy_report(), gcode=gcode).as_dict()
    assert payload["verdict"] == "ready"
    assert payload["banner"]["slicer"] == "PrusaSlicer"
    assert payload["gcode"]["slicer"] == "PrusaSlicer"
