"""Reading a sliced file back into a picture."""

from __future__ import annotations

from pathlib import Path

import pytest

from app.gcode.preview import (
    CACHE_VERSION,
    Feature,
    PreviewError,
    build_index,
    cache_path_for,
    classify,
    load_or_build_index,
    read_layer,
)


def write(path: Path, text: str) -> Path:
    path.write_text(text, encoding="utf-8")
    return path


PRUSA = """\
; generated by PrusaSlicer
G21
G90
M83
G28
;LAYER_CHANGE
;Z:0.2
;TYPE:Skirt/Brim
G1 X10 Y10 F9000
G1 X20 Y10 E0.5
G1 X20 Y20 E0.5
;TYPE:External perimeter
G1 X12 Y12 F9000
G1 X18 Y12 E0.4
G1 X18 Y18 E0.4
;TYPE:Internal infill
G1 X13 Y13 E0.2
G1 X17 Y17 E0.2
;LAYER_CHANGE
;Z:0.4
;TYPE:External perimeter
G1 X12 Y12 F9000
G1 X18 Y12 E0.4
;TYPE:Support material
G1 X30 Y30 E0.3
G1 X35 Y35 E0.3
"""

CURA = """\
;Generated with Cura
G90
;LAYER:0
;TYPE:WALL-OUTER
G1 X10 Y10 F9000
G1 X20 Y10 E0.5
;LAYER:1
;TYPE:FILL
G1 X11 Y11 E0.2
G1 X19 Y19 E0.2
"""


# --------------------------------------------------------------------------- #
# Feature classification
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("External perimeter", Feature.OUTER_WALL),      # PrusaSlicer
        ("Perimeter", Feature.INNER_WALL),
        ("Internal infill", Feature.INFILL),
        ("Solid infill", Feature.SOLID),
        ("Support material", Feature.SUPPORT),
        ("Skirt/Brim", Feature.SKIRT),
        ("Bridge infill", Feature.BRIDGE),
        ("Outer wall", Feature.OUTER_WALL),              # Orca / Bambu Studio
        ("Sparse infill", Feature.INFILL),
        ("Support interface", Feature.SUPPORT),
        ("WALL-OUTER", Feature.OUTER_WALL),              # Cura
        ("WALL-INNER", Feature.INNER_WALL),
        ("SKIN", Feature.SOLID),
        ("FILL", Feature.INFILL),
    ],
)
def test_every_slicers_spelling_lands_on_the_right_feature(raw, expected):
    assert classify(raw) == expected


def test_an_unseen_spelling_falls_back_on_the_words_rather_than_giving_up():
    # Every slicer release invents a new type name. Losing a whole feature to
    # "unknown" because of one is worse than reading the words.
    assert classify("Internal Bridge Infill") == Feature.BRIDGE
    assert classify("Tree Support Body") == Feature.SUPPORT
    assert classify("Overhang Wall Extra") == Feature.BRIDGE


def test_something_genuinely_unrecognisable_is_admitted_as_unknown():
    assert classify("Zorblax") == Feature.UNKNOWN


# --------------------------------------------------------------------------- #
# Indexing
# --------------------------------------------------------------------------- #


def test_the_index_finds_every_layer(tmp_path: Path):
    index = build_index(write(tmp_path / "a.gcode", PRUSA))
    assert index.layer_count == 2


def test_layer_heights_come_from_the_z_comment(tmp_path: Path):
    index = build_index(write(tmp_path / "a.gcode", PRUSA))
    assert index.layers[0].z == pytest.approx(0.2)
    assert index.layers[1].z == pytest.approx(0.4)


def test_cura_layer_markers_are_recognised_too(tmp_path: Path):
    # Cura numbers its layers and writes no ;Z:, so the heights are unknown -
    # which has to be reported as unknown rather than as zero.
    index = build_index(write(tmp_path / "c.gcode", CURA))
    assert index.layer_count == 2
    assert index.layers[0].z is None


def test_bounds_come_from_extruding_moves_only(tmp_path: Path):
    # The travel out to X200 must not set the extent: letting it would frame
    # the whole bed around a part in one corner.
    source = """\
G90
;LAYER_CHANGE
;TYPE:External perimeter
G1 X200 Y200 F9000
G1 X10 Y10 F9000
G1 X20 Y30 E0.5
"""
    index = build_index(write(tmp_path / "b.gcode", source))

    assert index.max_x == pytest.approx(20.0)
    assert index.max_y == pytest.approx(30.0)


def test_a_retraction_is_not_counted_as_extrusion(tmp_path: Path):
    source = """\
G90
;LAYER_CHANGE
;TYPE:Perimeter
G1 X10 Y10 E1.0
G1 X99 Y99 E-2.0
"""
    index = build_index(write(tmp_path / "r.gcode", source))

    # Negative E lays nothing down, so X99 is a travel and not the edge.
    assert index.max_x == pytest.approx(10.0)


def test_colour_change_layers_are_recorded_for_the_scrubber(tmp_path: Path):
    source = """\
G90
;LAYER_CHANGE
;TYPE:Perimeter
G1 X10 Y10 E1
;LAYER_CHANGE
;COLOR_CHANGE layer=2 color=Red
COLOR_CHANGE COLOR="Red" LAYER=2
;TYPE:Perimeter
G1 X12 Y12 E1
"""
    index = build_index(write(tmp_path / "cc.gcode", source))
    assert index.color_change_layers == [2]


def test_a_file_with_no_layer_markers_says_so(tmp_path: Path):
    with pytest.raises(PreviewError):
        build_index(write(tmp_path / "flat.gcode", "G90\nG1 X10 Y10 E1\n"))


def test_a_missing_file_is_refused(tmp_path: Path):
    with pytest.raises(PreviewError):
        build_index(tmp_path / "nope.gcode")


# --------------------------------------------------------------------------- #
# Reading a layer
# --------------------------------------------------------------------------- #


def test_a_layer_comes_back_split_by_feature(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    index = build_index(path)

    layer = read_layer(path, index, 0)
    features = [segment.feature for segment in layer.segments]

    assert Feature.SKIRT in features
    assert Feature.OUTER_WALL in features
    assert Feature.INFILL in features


def test_travel_moves_are_left_out_by_default(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    index = build_index(path)

    layer = read_layer(path, index, 0)

    # A layer with its travels drawn is a scribble.
    assert all(segment.feature != Feature.TRAVEL for segment in layer.segments)


def test_travel_moves_can_be_asked_for(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    index = build_index(path)

    layer = read_layer(path, index, 0, include_travel=True)

    assert any(segment.feature == Feature.TRAVEL for segment in layer.segments)


def test_a_segment_is_a_line_not_a_dot(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    index = build_index(path)

    layer = read_layer(path, index, 0)
    for segment in layer.segments:
        # Two coordinates per point, at least two points, or it draws nothing.
        assert len(segment.points) >= 4
        assert len(segment.points) % 2 == 0


def test_reading_the_second_layer_does_not_return_the_first(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    index = build_index(path)

    second = read_layer(path, index, 1)
    features = {segment.feature for segment in second.segments}

    # Support only appears on layer 2 in the fixture.
    assert Feature.SUPPORT in features
    assert Feature.SKIRT not in features


def test_the_layers_z_travels_with_it(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    index = build_index(path)

    assert read_layer(path, index, 1).z == pytest.approx(0.4)


def test_asking_for_a_layer_past_the_end_is_refused(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    index = build_index(path)

    with pytest.raises(PreviewError):
        read_layer(path, index, 99)
    with pytest.raises(PreviewError):
        read_layer(path, index, -1)


def test_relative_positioning_is_followed(tmp_path: Path):
    source = """\
G90
;LAYER_CHANGE
;TYPE:Perimeter
G1 X10 Y10 E1
G91
G1 X5 Y0 E1
G1 X0 Y5 E1
"""
    path = write(tmp_path / "rel.gcode", source)
    index = build_index(path)
    layer = read_layer(path, index, 0)

    points = [value for segment in layer.segments for value in segment.points]
    # 10 then +5 then +5 in Y: the far corner is (15, 15), not (5, 5).
    assert max(points[0::2]) == pytest.approx(15.0)
    assert max(points[1::2]) == pytest.approx(15.0)


# --------------------------------------------------------------------------- #
# Caching
# --------------------------------------------------------------------------- #


def test_the_index_is_cached_and_reused(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    cache = tmp_path / "cache"

    first = load_or_build_index(path, cache)
    assert cache_path_for(path, cache).is_file()

    second = load_or_build_index(path, cache)
    assert second.layer_count == first.layer_count
    assert second.version == CACHE_VERSION


def test_a_cache_for_a_replaced_file_is_rebuilt(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    cache = tmp_path / "cache"
    load_or_build_index(path, cache)

    # Same name, different contents: the recorded offsets no longer mean
    # anything, and seeking to them would return the wrong layer.
    write(path, CURA)
    rebuilt = load_or_build_index(path, cache)

    assert rebuilt.layer_count == 2
    assert rebuilt.file_size == path.stat().st_size


def test_a_corrupt_cache_is_discarded_rather_than_trusted(tmp_path: Path):
    path = write(tmp_path / "a.gcode", PRUSA)
    cache = tmp_path / "cache"
    load_or_build_index(path, cache)
    cache_path_for(path, cache).write_text("{ not json", encoding="utf-8")

    assert load_or_build_index(path, cache).layer_count == 2


def test_an_unwritable_cache_directory_does_not_stop_the_preview(tmp_path: Path, monkeypatch):
    path = write(tmp_path / "a.gcode", PRUSA)

    def refuse(*args, **kwargs):
        raise OSError("disk full")

    monkeypatch.setattr(Path, "write_text", refuse)

    # A full disk means the next open pays for the scan again - it does not
    # mean the preview is unavailable.
    assert load_or_build_index(path, tmp_path / "cache").layer_count == 2
