"""Multi-colour printing: placing filament swaps into a sliced file.

The three engines write layers differently and the difference matters, because
getting the layer number wrong by one puts the colour boundary on the wrong side
of a visible line. Both dialects are tested against the same expectations.
"""

from __future__ import annotations

import textwrap

import pytest

from app.klipper.macros import has_color_change_macro, suggest_color_change
from app.klipper.model import parse_config
from app.slicer.colors import (
    COLOR_CHANGE_COMMAND,
    ColorChangeError,
    apply_color_changes,
    clean_color_name,
    color_from_display,
    parse_manifest,
    scan_layers,
)

PRUSA = textwrap.dedent(
    """\
    ; generated by PrusaSlicer 2.7.4
    M190 S60
    M109 S210
    ;LAYER_CHANGE
    ;Z:0.2
    G1 X10 Y10 E1
    ;LAYER_CHANGE
    ;Z:0.4
    G1 X20 Y20 E2
    ;LAYER_CHANGE
    ;Z:0.6
    G1 X30 Y30 E3
    ;LAYER_CHANGE
    ;Z:0.8
    G1 X40 Y40 E4
    M107
    """
)

CURA = textwrap.dedent(
    """\
    ;Generated with Cura_SteamEngine 5.6.0
    M190 S60
    ;LAYER:0
    G0 F3000 X10 Y10 Z0.3
    G1 X11 Y11 E1
    ;LAYER:1
    G0 F3000 X20 Y20 Z0.5
    G1 X21 Y21 E2
    ;LAYER:2
    G0 F3000 X30 Y30 Z0.7
    G1 X31 Y31 E3
    """
)


def write(tmp_path, text, name="part.gcode"):
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


# --------------------------------------------------------------------------- #
# Layer indexing
# --------------------------------------------------------------------------- #


def test_prusa_layers_are_counted_from_one(tmp_path):
    marks = scan_layers(write(tmp_path, PRUSA))
    assert [m.number for m in marks] == [1, 2, 3, 4]
    assert [m.z for m in marks] == [0.2, 0.4, 0.6, 0.8]


def test_cura_layers_are_renumbered_from_zero(tmp_path):
    """Cura's first layer is ;LAYER:0, and a person's first layer is 1."""
    marks = scan_layers(write(tmp_path, CURA))
    assert [m.number for m in marks] == [1, 2, 3]
    # Cura has no ;Z: comment - the height comes from the layer's own move.
    assert [m.z for m in marks] == [0.3, 0.5, 0.7]


def test_a_file_with_no_layers_indexes_to_nothing(tmp_path):
    assert scan_layers(write(tmp_path, "G28\nM84\n")) == []


# --------------------------------------------------------------------------- #
# Placing the changes
# --------------------------------------------------------------------------- #


def test_change_goes_before_the_layer_it_starts(tmp_path):
    """Everything below the change is the old colour; the named layer is new."""
    path = write(tmp_path, PRUSA)
    applied = apply_color_changes(path, [(3, "أحمر")])

    assert [(c.layer, c.color, c.z) for c in applied] == [(3, "أحمر", 0.6)]

    lines = path.read_text(encoding="utf-8").splitlines()
    call = next(i for i, line in enumerate(lines) if line.startswith(COLOR_CHANGE_COMMAND))
    # The third ;LAYER_CHANGE must come after the call, and the second before.
    markers = [i for i, line in enumerate(lines) if line.startswith(";LAYER_CHANGE")]
    assert markers[1] < call < markers[2]
    # And the move that belongs to layer 2 is still above it.
    assert lines.index("G1 X20 Y20 E2") < call


def test_the_call_carries_the_colour_and_the_layer(tmp_path):
    path = write(tmp_path, PRUSA)
    apply_color_changes(path, [(2, "Light Blue")])
    text = path.read_text(encoding="utf-8")

    # Quoted, because Klipper parses extended parameters with shlex and a bare
    # "Light Blue" would arrive as COLOR=Light with a stray argument.
    assert 'COLOR_CHANGE COLOR="Light Blue" LAYER=2' in text
    assert "M117 COLOR: Light Blue" in text
    assert ";COLOR_CHANGE layer=2 color=Light Blue" in text


def test_several_changes_land_on_their_own_layers(tmp_path):
    path = write(tmp_path, PRUSA)
    applied = apply_color_changes(path, [(4, "أزرق"), (2, "أحمر")])
    # Sorted, whatever order they were asked for in.
    assert [c.layer for c in applied] == [2, 4]
    text = path.read_text(encoding="utf-8")
    assert text.index('COLOR="أحمر"') < text.index('COLOR="أزرق"')


def test_cura_files_take_changes_too(tmp_path):
    path = write(tmp_path, CURA)
    applied = apply_color_changes(path, [(2, "green")])
    assert applied[0].z == 0.5
    lines = path.read_text(encoding="utf-8").splitlines()
    call = next(i for i, line in enumerate(lines) if line.startswith(COLOR_CHANGE_COMMAND))
    assert lines[call + 1] == ";LAYER:1"


def test_nothing_is_written_when_nothing_is_asked_for(tmp_path):
    path = write(tmp_path, PRUSA)
    assert apply_color_changes(path, []) == []
    assert path.read_text(encoding="utf-8") == PRUSA


# --------------------------------------------------------------------------- #
# Refusals - each one is a print that would otherwise fail hours in
# --------------------------------------------------------------------------- #


def test_a_layer_past_the_end_is_refused(tmp_path):
    path = write(tmp_path, PRUSA)
    with pytest.raises(ColorChangeError) as excinfo:
        apply_color_changes(path, [(90, "red")])
    assert "4 layers" in str(excinfo.value)
    # And the file is untouched, so the print is still usable in one colour.
    assert path.read_text(encoding="utf-8") == PRUSA


def test_a_change_at_the_first_layer_is_refused(tmp_path):
    with pytest.raises(ColorChangeError):
        apply_color_changes(write(tmp_path, PRUSA), [(1, "red")])


def test_two_changes_on_one_layer_are_refused(tmp_path):
    with pytest.raises(ColorChangeError):
        apply_color_changes(write(tmp_path, PRUSA), [(2, "red"), (2, "blue")])


def test_a_file_without_layer_markers_is_refused(tmp_path):
    with pytest.raises(ColorChangeError) as excinfo:
        apply_color_changes(write(tmp_path, "G28\nM84\n"), [(2, "red")])
    assert "no layer markers" in str(excinfo.value)


def test_a_name_that_is_only_punctuation_is_refused(tmp_path):
    with pytest.raises(ColorChangeError):
        apply_color_changes(write(tmp_path, PRUSA), [(2, ";;;")])


# --------------------------------------------------------------------------- #
# Names, manifest and the display message
# --------------------------------------------------------------------------- #


def test_a_name_cannot_end_the_gcode_line_early():
    """A semicolon in a colour name would comment out the rest of the command."""
    assert clean_color_name('red; M112') == "red M112"
    assert '"' not in clean_color_name('re"d')


def test_the_plan_is_readable_back_from_the_file(tmp_path):
    path = write(tmp_path, PRUSA)
    apply_color_changes(path, [(2, "أحمر"), (4, "أزرق")])
    plan = parse_manifest(path.read_text(encoding="utf-8"))
    assert [(c.layer, c.color) for c in plan] == [(2, "أحمر"), (4, "أزرق")]


def test_a_file_with_no_plan_reads_back_as_empty():
    assert parse_manifest(PRUSA) == []


def test_the_paused_colour_comes_from_the_display_message():
    assert color_from_display("COLOR: أحمر") == "أحمر"
    assert color_from_display("Printing 40%") is None
    assert color_from_display("") is None


# --------------------------------------------------------------------------- #
# The macro
# --------------------------------------------------------------------------- #

BED_SLINGER = """
[pause_resume]

[stepper_x]
position_min: -8.3
position_max: 330

[stepper_y]
position_min: -1.3
position_max: 330

[stepper_z]
position_max: 400

[extruder]
min_extrude_temp: 170
"""


def test_pause_comes_before_the_parking_moves():
    """The single most consequential line order in the macro.

    [pause_resume] records where the toolhead is when PAUSE runs, and RESUME
    returns there. Park first and the print resumes from the parking corner.
    """
    suggestion = suggest_color_change(parse_config(BED_SLINGER))
    assert suggestion.ok
    body = suggestion.gcode
    assert body.index("\n    PAUSE") < body.index("G1 E-")
    assert body.index("\n    PAUSE") < body.index("G1 X")


def test_the_macro_announces_the_colour_before_it_stops():
    body = suggest_color_change(parse_config(BED_SLINGER)).gcode
    assert body.index("M117 COLOR:") < body.index("\n    PAUSE")


def test_the_macro_parks_inside_the_configured_travel():
    body = suggest_color_change(parse_config(BED_SLINGER)).gcode
    # position_min is negative here - homing overtravel, not bed - so the park
    # must be measured from the bed origin.
    assert "G1 X5.0 Y5.0" in body


def test_without_pause_resume_the_macro_is_refused():
    suggestion = suggest_color_change(parse_config("[extruder]\nmin_extrude_temp: 170\n"))
    assert not suggestion.ok
    assert "pause_resume" in suggestion.blockers[0]
    assert suggestion.gcode == ""


def test_an_existing_macro_is_reported_rather_than_overwritten():
    config = parse_config(BED_SLINGER + "\n[gcode_macro COLOR_CHANGE]\ngcode:\n    M117 hi\n")
    assert has_color_change_macro(config)
    assert suggest_color_change(config).conflicts


def test_a_printer_without_the_macro_says_so():
    assert not has_color_change_macro(parse_config(BED_SLINGER))
