from __future__ import annotations

import asyncio
import textwrap
from pathlib import Path

import pytest

from app.schemas import SliceRequest
from app.slicer import ProfileStore, SliceJobManager, build_engine, parse_gcode
from app.slicer.engine import (
    OrcaSlicerEngine,
    PrusaSlicerEngine,
    SlicerError,
    bed_center,
    build_orca_overrides,
    build_prusa_overrides,
    stats_from_gcode,
    write_override_ini,
)
from app.slicer.gcode_meta import parse_duration
from app.slicer.profiles import parse_ini
from app.storage import GCodeStore, ModelStore

PROFILES_DIR = Path(__file__).resolve().parent.parent / "profiles"

SAMPLE_GCODE = textwrap.dedent(
    """\
    ; generated by PrusaSlicer 2.7.4+linux-aarch64 on 2026-08-07
    ; layer_height = 0.2
    M190 S60
    M109 S210
    ;LAYER_CHANGE
    G1 X10 Y10 E1
    ;LAYER_CHANGE
    G1 X20 Y20 E2
    ;LAYER_CHANGE
    G1 X30 Y30 E3
    M107
    ; filament used [mm] = 4321.5
    ; filament used [cm3] = 10.39
    ; filament used [g] = 12.88
    ; total filament used [g] = 12.88
    ; estimated printing time (normal mode) = 1h 24m 13s
    ; total layers count = 118
    ; filament_type = PLA
    ; max_print_height = 42.6
    """
)


# --------------------------------------------------------------------------- #
# Profiles
# --------------------------------------------------------------------------- #


def test_shipped_profiles_load():
    store = ProfileStore(PROFILES_DIR)
    printers = {p.id for p in store.list("printer")}
    filaments = {p.id for p in store.list("filament")}
    prints = {p.id for p in store.list("print")}

    assert {"neptune3plus_0.2", "neptune3plus_0.4", "neptune3plus_0.6", "neptune3plus_0.8"} <= printers
    assert {"pla", "pla_plus", "petg", "tpu", "asa", "abs", "custom"} <= filaments
    assert {"quality", "standard", "fast", "klipper_fast", "custom"} <= prints


def test_neptune_printer_profile_matches_the_hardware():
    store = ProfileStore(PROFILES_DIR)
    profile = store.require("printer", "neptune3plus_0.4")
    assert profile.values["bed_shape"] == "0x0,320x0,320x320,0x320"
    assert profile.values["max_print_height"] == "400"
    assert profile.values["nozzle_diameter"] == "0.4"
    assert profile.values["gcode_flavor"] == "klipper"
    assert "300x300" in profile.values["thumbnails"]
    assert profile.name.startswith("Elegoo Neptune 3 Plus")


def test_nozzle_variants_differ_only_where_expected():
    store = ProfileStore(PROFILES_DIR)
    for profile_id, diameter in (
        ("neptune3plus_0.2", "0.2"),
        ("neptune3plus_0.6", "0.6"),
        ("neptune3plus_0.8", "0.8"),
    ):
        profile = store.require("printer", profile_id)
        assert profile.values["nozzle_diameter"] == diameter
        assert profile.values["max_print_height"] == "400"


def test_tpu_profile_is_conservative():
    store = ProfileStore(PROFILES_DIR)
    tpu = store.require("filament", "tpu")
    pla = store.require("filament", "pla")
    assert float(tpu.values["filament_max_volumetric_speed"]) < float(
        pla.values["filament_max_volumetric_speed"]
    )
    assert float(tpu.values["filament_max_volumetric_speed"]) <= 2.0
    assert tpu.values["filament_type"] == "FLEX"


def test_print_profiles_carry_every_documented_speed_key():
    store = ProfileStore(PROFILES_DIR)
    required = {
        "perimeter_speed",
        "external_perimeter_speed",
        "infill_speed",
        "solid_infill_speed",
        "top_solid_infill_speed",
        "first_layer_speed",
        "travel_speed",
        "default_acceleration",
    }
    for profile in store.list("print"):
        assert required <= set(profile.values), f"{profile.id} is missing keys"


def test_speed_profiles_are_ordered():
    store = ProfileStore(PROFILES_DIR)
    speeds = {p.id: float(p.values["perimeter_speed"]) for p in store.list("print")}
    assert speeds["quality"] < speeds["standard"] < speeds["fast"] < speeds["klipper_fast"]


def test_missing_profile_raises_with_available_list():
    store = ProfileStore(PROFILES_DIR)
    with pytest.raises(FileNotFoundError) as excinfo:
        store.require("filament", "unobtanium")
    assert "available" in str(excinfo.value)


def test_parse_ini_reads_metadata_comments():
    values, name, description = parse_ini("# name: X\n# description: Y\nkey = value\n; ignored\n")
    assert name == "X"
    assert description == "Y"
    assert values == {"key": "value"}


def test_bed_center_from_bed_shape():
    store = ProfileStore(PROFILES_DIR)
    assert bed_center(store.require("printer", "neptune3plus_0.4")) == "160,160"


# --------------------------------------------------------------------------- #
# Overrides
# --------------------------------------------------------------------------- #


def test_prusa_overrides_map_every_request_field():
    request = SliceRequest(
        model_id="abc",
        layer_height=0.16,
        first_layer_height=0.24,
        nozzle_diameter=0.4,
        infill_percent=35,
        infill_pattern="gyroid",
        perimeters=4,
        supports=True,
        support_style="organic",
        adhesion="brim",
        brim_width=8,
        nozzle_temperature=215,
        first_layer_nozzle_temperature=220,
        bed_temperature=62,
        first_layer_bed_temperature=65,
        retraction_length=1.2,
        retraction_speed=45,
        speed_profile_overrides={"perimeter": 55, "acceleration": 4000},
        custom_overrides={"seam_position": "rear"},
    )
    overrides = build_prusa_overrides(request)
    assert overrides["layer_height"] == "0.16"
    assert overrides["first_layer_height"] == "0.24"
    assert overrides["fill_density"] == "35%"
    assert overrides["fill_pattern"] == "gyroid"
    assert overrides["perimeters"] == "4"
    assert overrides["support_material"] == "1"
    assert overrides["support_material_style"] == "organic"
    assert overrides["brim_width"] == "8"
    assert overrides["temperature"] == "215"
    assert overrides["first_layer_temperature"] == "220"
    assert overrides["bed_temperature"] == "62"
    assert overrides["first_layer_bed_temperature"] == "65"
    assert overrides["retract_length"] == "1.2"
    assert overrides["retract_speed"] == "45"
    assert overrides["perimeter_speed"] == "55"
    assert overrides["default_acceleration"] == "4000"
    assert overrides["seam_position"] == "rear"


def test_supports_disabled_is_explicit():
    overrides = build_prusa_overrides(SliceRequest(model_id="x", supports=False))
    assert overrides["support_material"] == "0"


def test_custom_overrides_win():
    request = SliceRequest(model_id="x", layer_height=0.2, custom_overrides={"layer_height": "0.3"})
    assert build_prusa_overrides(request)["layer_height"] == "0.3"


def test_orca_overrides_use_orca_key_names():
    request = SliceRequest(
        model_id="x",
        layer_height=0.2,
        infill_percent=20,
        perimeters=3,
        supports=True,
        speed_profile_overrides={"external_perimeter": 40},
    )
    overrides = build_orca_overrides(request)
    assert overrides["layer_height"] == 0.2
    assert overrides["sparse_infill_density"] == "20%"
    assert overrides["wall_loops"] == 3
    assert overrides["enable_support"] is True
    assert overrides["outer_wall_speed"] == 40


def test_write_override_ini_is_sorted_and_readable(tmp_path: Path):
    path = write_override_ini(tmp_path / "o.ini", {"b": "2", "a": "1"})
    lines = [line for line in path.read_text().splitlines() if not line.startswith("#")]
    assert lines == ["a = 1", "b = 2"]
    values, _, _ = parse_ini(path.read_text())
    assert values == {"a": "1", "b": "2"}


# --------------------------------------------------------------------------- #
# G-code metadata
# --------------------------------------------------------------------------- #


def test_parse_duration_variants():
    assert parse_duration("1h 24m 13s") == 5053
    assert parse_duration("2d 1h") == 176400
    assert parse_duration("45s") == 45
    assert parse_duration("3600") == 3600
    assert parse_duration("") is None
    assert parse_duration("soon") is None


def test_parse_gcode_extracts_stats(tmp_path: Path):
    path = tmp_path / "out.gcode"
    path.write_text(SAMPLE_GCODE, encoding="utf-8")
    meta = parse_gcode(path)
    assert meta["estimated_time"] == 5053
    assert meta["filament_grams"] == pytest.approx(12.88)
    assert meta["filament_mm"] == pytest.approx(4321.5)
    assert meta["filament_cm3"] == pytest.approx(10.39)
    assert meta["layer_count"] == 118
    assert meta["layer_height"] == pytest.approx(0.2)
    assert meta["filament_type"] == "PLA"
    assert "PrusaSlicer" in str(meta["slicer"])
    assert meta["gcode_size"] > 0


def test_stats_from_gcode_converts_to_meters(tmp_path: Path):
    path = tmp_path / "out.gcode"
    path.write_text(SAMPLE_GCODE, encoding="utf-8")
    stats = stats_from_gcode(path)
    assert stats.filament_meters == pytest.approx(4.3215)
    assert stats.filament_grams == pytest.approx(12.88)
    assert stats.estimated_time_seconds == 5053
    assert stats.layer_count == 118


def test_layer_count_falls_back_to_layer_changes(tmp_path: Path):
    path = tmp_path / "out.gcode"
    path.write_text(SAMPLE_GCODE.replace("; total layers count = 118", ""), encoding="utf-8")
    assert parse_gcode(path)["layer_count"] == 3


def test_parse_gcode_of_missing_file_is_empty(tmp_path: Path):
    assert parse_gcode(tmp_path / "nope.gcode") == {}


# --------------------------------------------------------------------------- #
# Engine selection and job manager
# --------------------------------------------------------------------------- #


def test_build_engine_picks_the_requested_engine():
    store = ProfileStore(PROFILES_DIR)
    kwargs = dict(prusaslicer_bin="prusa-slicer", orcaslicer_bin="orca-slicer", timeout=60)
    assert isinstance(build_engine("prusaslicer", store, **kwargs), PrusaSlicerEngine)
    assert isinstance(build_engine("orca-slicer", store, **kwargs), OrcaSlicerEngine)
    assert isinstance(build_engine("", store, **kwargs), PrusaSlicerEngine)


def test_missing_binary_is_reported_not_crashed():
    store = ProfileStore(PROFILES_DIR)
    engine = PrusaSlicerEngine("definitely-not-installed-slicer", store, 30)
    assert engine.available is False
    assert engine.resolve_binary() is None


@pytest.mark.asyncio
async def test_job_manager_reports_a_missing_slicer_as_a_failed_job(tmp_path: Path):
    models = ModelStore(tmp_path / "models")
    gcodes = GCodeStore(tmp_path / "gcode")
    model = models.save("cube.stl", b"solid cube\nendsolid cube\n")

    engine = PrusaSlicerEngine("definitely-not-installed-slicer", ProfileStore(PROFILES_DIR), 30)
    manager = SliceJobManager(engine, models, gcodes)

    seen: list[str] = []

    async def listener(job):
        seen.append(job.status)

    manager.add_listener(listener)
    job = manager.submit(SliceRequest(model_id=model.id))
    for _ in range(50):
        await asyncio.sleep(0.02)
        if job.status in {"failed", "done"}:
            break

    assert job.status == "failed"
    assert "not found" in (job.error or "")
    assert "failed" in seen


@pytest.mark.asyncio
async def test_job_manager_rejects_unknown_model(tmp_path: Path):
    manager = SliceJobManager(
        PrusaSlicerEngine("x", ProfileStore(PROFILES_DIR), 30),
        ModelStore(tmp_path / "m"),
        GCodeStore(tmp_path / "g"),
    )
    with pytest.raises(FileNotFoundError):
        manager.submit(SliceRequest(model_id="missing"))


@pytest.mark.asyncio
async def test_job_manager_rejects_unsupported_extension(tmp_path: Path):
    models = ModelStore(tmp_path / "m")
    model = models.save("notes.txt", b"hello")
    manager = SliceJobManager(
        PrusaSlicerEngine("x", ProfileStore(PROFILES_DIR), 30), models, GCodeStore(tmp_path / "g")
    )
    with pytest.raises(ValueError):
        manager.submit(SliceRequest(model_id=model.id))


@pytest.mark.asyncio
async def test_orca_engine_explains_missing_json_profiles(tmp_path: Path):
    engine = OrcaSlicerEngine("orca-slicer", ProfileStore(PROFILES_DIR), 30)
    with pytest.raises(SlicerError) as excinfo:
        await engine.slice(
            tmp_path / "m.stl", tmp_path / "o.gcode", SliceRequest(model_id="x"), tmp_path
        )
    assert "profiles/orca" in str(excinfo.value)


class TestSlicerVerification:
    """A slicer that exists but cannot run must not report itself available.

    PrusaSlicer aborts at startup when the inherited locale has not been
    generated on the host - the default state of a fresh Raspberry Pi OS image,
    and also what happens when an SSH client forwards a locale the Pi lacks.
    Checking only that the binary exists reported slicing as working and let the
    failure surface later, deep inside a job.
    """

    def test_environment_pins_a_locale_that_always_exists(self, tmp_path):
        from app.slicer.engine import PrusaSlicerEngine
        from app.slicer.profiles import ProfileStore

        engine = PrusaSlicerEngine("prusa-slicer", ProfileStore(tmp_path))
        env = engine.subprocess_env()
        assert env["LC_ALL"] == "C"
        assert env["LANG"] == "C"
        # Still headless, and still able to find its own libraries.
        assert env["QT_QPA_PLATFORM"] == "offscreen"
        assert "PATH" in env

    async def test_missing_binary_verifies_false_with_a_reason(self, tmp_path):
        from app.slicer.engine import PrusaSlicerEngine
        from app.slicer.profiles import ProfileStore

        engine = PrusaSlicerEngine("definitely-not-a-real-slicer", ProfileStore(tmp_path))
        assert await engine.verify() is False
        assert "not found" in engine.verify_error.lower()

    async def test_binary_that_exits_nonzero_verifies_false(self, tmp_path):
        """Stands in for the locale crash: present, executable, dies at once."""
        from app.slicer.engine import PrusaSlicerEngine
        from app.slicer.profiles import ProfileStore

        broken = tmp_path / "broken-slicer"
        broken.write_text(
            "#!/bin/sh\n"
            "echo 'An error occured while setting up locale.' >&2\n"
            "echo 'locale::facet::_S_create_c_locale name not valid' >&2\n"
            "exit 2\n"
        )
        broken.chmod(0o755)

        engine = PrusaSlicerEngine(str(broken), ProfileStore(tmp_path))
        assert engine.available is True, "the file is there"
        assert await engine.verify() is False, "but it cannot run"
        assert "locale" in engine.verify_error.lower()

    async def test_verification_is_cached(self, tmp_path):
        from app.slicer.engine import PrusaSlicerEngine
        from app.slicer.profiles import ProfileStore

        counter = tmp_path / "counter"
        script = tmp_path / "counting-slicer"
        script.write_text(f"#!/bin/sh\necho x >> {counter}\nexit 0\n")
        script.chmod(0o755)

        engine = PrusaSlicerEngine(str(script), ProfileStore(tmp_path))
        assert await engine.verify() is True
        assert await engine.verify() is True
        assert counter.read_text().count("x") == 1, "cached after the first run"

        await engine.verify(force=True)
        assert counter.read_text().count("x") == 2


class TestSupportPlacement:
    """Where support may start from, which the app could not express at all.

    Style - grid, snug, organic - is the shape of the support and the less
    consequential of the two choices. Support that grows off the model marks
    whatever surface it stood on, and no style setting undoes that.
    """

    def _request(self, **kwargs):
        from app.schemas import SliceRequest

        return SliceRequest(model_id="m", supports=True, **kwargs)

    def test_build_plate_only_reaches_prusa(self):
        from app.slicer.engine import build_prusa_overrides

        out = build_prusa_overrides(self._request(support_placement="build_plate_only"))
        assert out["support_material_buildplate_only"] == "1"

    def test_everywhere_is_sent_explicitly_rather_than_left_to_a_default(self):
        from app.slicer.engine import build_prusa_overrides

        out = build_prusa_overrides(self._request(support_placement="everywhere"))
        assert out["support_material_buildplate_only"] == "0"

    def test_orca_gets_its_own_key_names(self):
        from app.slicer.engine import build_orca_overrides

        out = build_orca_overrides(
            self._request(support_placement="build_plate_only", support_threshold_angle=55)
        )
        assert out["support_on_build_plate_only"] is True
        assert out["support_threshold_angle"] == 55

    def test_nothing_support_related_is_sent_when_support_is_off(self):
        from app.schemas import SliceRequest
        from app.slicer.engine import build_prusa_overrides

        out = build_prusa_overrides(
            SliceRequest(
                model_id="m",
                supports=False,
                support_placement="build_plate_only",
                support_threshold_angle=55,
            )
        )
        assert out["support_material"] == "0"
        assert "support_material_buildplate_only" not in out
        assert "support_material_threshold" not in out

    def test_an_unset_angle_leaves_the_engine_default_alone(self):
        from app.slicer.engine import build_prusa_overrides

        out = build_prusa_overrides(self._request())
        assert "support_material_threshold" not in out


class TestExpandedOptions:
    """The settings the app could not express, and what "unset" has to mean.

    Every one of these is optional, and the rule throughout is that a value
    the user never chose is never sent: overriding a printer profile silently
    is worse than not offering the setting at all.
    """

    def _request(self, **kwargs):
        from app.schemas import SliceRequest

        return SliceRequest(model_id="m", **kwargs)

    def test_nothing_extra_is_sent_when_nothing_was_chosen(self):
        from app.slicer.engine import build_prusa_overrides

        out = build_prusa_overrides(self._request())
        for key in (
            "top_solid_layers", "bottom_solid_layers", "ironing", "seam_position",
            "spiral_vase", "retract_lift", "min_fan_speed", "max_fan_speed",
            "disable_fan_first_layers", "avoid_crossing_perimeters", "fill_pattern",
        ):
            assert key not in out, key

    def test_shell_and_surface_reach_prusa(self):
        from app.slicer.engine import build_prusa_overrides

        out = build_prusa_overrides(
            self._request(
                top_solid_layers=5,
                bottom_solid_layers=4,
                seam_position="rear",
                infill_pattern="gyroid",
                retraction_z_hop=0.4,
            )
        )
        assert out["top_solid_layers"] == "5"
        assert out["bottom_solid_layers"] == "4"
        assert out["seam_position"] == "rear"
        assert out["fill_pattern"] == "gyroid"
        assert out["retract_lift"] == "0.4"

    def test_booleans_use_each_engines_own_spelling(self):
        """Orca does not have an on/off ironing flag; it names the surfaces."""
        from app.slicer.engine import build_orca_overrides, build_prusa_overrides

        request = self._request(ironing=True, spiral_vase=True, avoid_crossing_perimeters=True)
        prusa = build_prusa_overrides(request)
        orca = build_orca_overrides(request)

        assert prusa["ironing"] == "1"
        assert prusa["spiral_vase"] == "1"
        assert prusa["avoid_crossing_perimeters"] == "1"

        assert orca["ironing_type"] == "top"
        assert orca["spiral_mode"] is True
        assert orca["reduce_crossing_wall"] is True

    def test_ironing_off_is_sent_as_off_not_omitted(self):
        """False is a choice; None is not. They must not collapse together."""
        from app.slicer.engine import build_orca_overrides, build_prusa_overrides

        request = self._request(ironing=False)
        assert build_prusa_overrides(request)["ironing"] == "0"
        assert build_orca_overrides(request)["ironing_type"] == "no ironing"

    def test_cooling_reaches_both_engines(self):
        from app.slicer.engine import build_orca_overrides, build_prusa_overrides

        request = self._request(
            fan_min_percent=30, fan_max_percent=100, disable_fan_first_layers=2
        )
        prusa = build_prusa_overrides(request)
        orca = build_orca_overrides(request)
        assert prusa["min_fan_speed"] == "30"
        assert prusa["disable_fan_first_layers"] == "2"
        assert orca["fan_max_speed"] == 100
        assert orca["close_fan_the_first_x_layers"] == 2

    def test_raw_overrides_still_win_over_everything(self):
        from app.slicer.engine import build_prusa_overrides

        out = build_prusa_overrides(
            self._request(top_solid_layers=5, custom_overrides={"top_solid_layers": "9"})
        )
        assert out["top_solid_layers"] == "9"
