"""Static G-code analysis.

This module exists because a mismatched slicer profile once produced a print in
the wrong physical location. Every test here is a shape of that failure.

Note what is *not* tested: any ability to rewrite G-code. The analyser has no
such function - it reads and reports, and nothing more.
"""

from __future__ import annotations

import pytest

from app.gcode.validator import GCodeVerdict, analyse_gcode, analyse_gcode_file
from app.klipper.model import parse_config

CONFIG = parse_config(
    """
[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000

[stepper_x]
position_min: -3
position_max: 330

[stepper_y]
position_min: -8
position_max: 330

[stepper_z]
position_min: 0
position_max: 410

[extruder]
nozzle_diameter: 0.4
"""
)

GOLDEN = ["Neptune3Plus 0.20 Standard"]

HEADER = """; generated by PrusaSlicer 2.8.1+linux on 2026-01-01 at 10:00:00
; layer_height = 0.2
; first_layer_height = 0.25
; nozzle_diameter = 0.4
; print_settings_id = Neptune3Plus 0.20 Standard
; filament_settings_id = Generic PLA
"""

BODY = """G90
M83
M104 S210
M140 S60
G28
M204 S3000
G1 X10 Y10 Z0.2 F1800
G1 X300 Y300 E5 F3000
"""


def good(extra: str = "", header: str = HEADER, body: str = BODY) -> str:
    return header + body + extra


def analyse(text: str, **kwargs):
    kwargs.setdefault("config", CONFIG)
    kwargs.setdefault("golden_profiles", GOLDEN)
    return analyse_gcode(text, **kwargs)


# --------------------------------------------------------------------------- #
# The happy path
# --------------------------------------------------------------------------- #


def test_a_clean_prusaslicer_file_is_safe():
    report = analyse(good())
    assert report.verdict is GCodeVerdict.SAFE
    assert report.issues == []
    assert report.slicer == "PrusaSlicer"
    assert report.slicer_version.startswith("2.8.1")
    assert report.verified_profile is True
    assert report.profile_status == "golden"


def test_metadata_is_extracted():
    report = analyse(good())
    assert report.layer_height == 0.2
    assert report.first_layer_height == 0.25
    assert report.nozzle_diameter == 0.4
    assert report.profile_name == "Neptune3Plus 0.20 Standard"
    assert report.filament == "Generic PLA"


def test_bounds_are_measured():
    report = analyse(good())
    assert report.bounds.min_x == 10.0
    assert report.bounds.max_x == 300.0
    assert report.bounds.max_z == 0.2


# --------------------------------------------------------------------------- #
# Build volume - checked against the LIVE config
# --------------------------------------------------------------------------- #


def test_a_move_beyond_the_configured_maximum_is_blocked():
    report = analyse(good("G1 X400 Y10\n"))
    assert report.verdict is GCodeVerdict.BLOCKED
    assert any(i.code == "outside_build_volume" for i in report.errors)


def test_a_move_below_the_configured_minimum_is_blocked():
    report = analyse(good("G1 X-50 Y10\n"))
    assert report.verdict is GCodeVerdict.BLOCKED


def test_bounds_are_judged_by_the_live_config_not_the_printer_model():
    """A 330 mm move is fine on this printer, and out of range on a smaller one."""
    small = parse_config(
        "[printer]\n[stepper_x]\nposition_min: 0\nposition_max: 220\n"
        "[stepper_y]\nposition_min: 0\nposition_max: 220\n"
        "[stepper_z]\nposition_min: 0\nposition_max: 250\n"
    )
    assert analyse(good()).verdict is GCodeVerdict.SAFE
    report = analyse_gcode(good(), config=small, golden_profiles=GOLDEN)
    assert report.verdict is GCodeVerdict.BLOCKED


def test_without_a_live_config_the_volume_check_is_reported_as_skipped():
    report = analyse_gcode(good(), config=None, golden_profiles=GOLDEN)
    assert any(i.code == "limits_unknown" for i in report.issues)
    assert report.verdict is GCodeVerdict.WARNING


def test_relative_moves_are_resolved_to_absolute_positions():
    text = HEADER + "G90\nM83\nG28\nG1 X10 Y10\nG91\nG1 X100\nG1 X100\n"
    report = analyse(text)
    # 10 + 100 + 100 = 210, not three separate 100s.
    assert report.bounds.max_x == pytest.approx(210.0)


def test_g92_origin_shifts_are_accounted_for():
    """A G92 that redefines the origin must not hide a move off the bed."""
    text = HEADER + "G90\nM83\nG28\nG1 X300 Y10\nG92 X0\nG1 X100\n"
    report = analyse(text)
    # After G92 X0 at machine X=300, "X100" is really machine X=400.
    assert report.bounds.max_x == pytest.approx(400.0)
    assert report.verdict is GCodeVerdict.BLOCKED


# --------------------------------------------------------------------------- #
# Positioning and extrusion modes
# --------------------------------------------------------------------------- #


def test_a_file_without_g90_or_g91_is_blocked():
    report = analyse(HEADER + "M83\nG28\nG1 X10 Y10 F1800\n")
    assert report.verdict is GCodeVerdict.BLOCKED
    assert any(i.code == "no_positioning_mode" for i in report.errors)


def test_a_file_that_never_homes_is_blocked():
    report = analyse(HEADER + "G90\nM83\nM104 S210\nG1 X10 Y10 F1800\n")
    assert report.verdict is GCodeVerdict.BLOCKED
    assert any(i.code == "no_homing" for i in report.errors)


def test_a_missing_extrusion_mode_warns():
    report = analyse(HEADER + "G90\nM104 S210\nG28\nG1 X10 Y10 F1800\n")
    assert any(i.code == "no_extrusion_mode" for i in report.warnings)


def test_a_file_with_no_motion_is_blocked():
    report = analyse(HEADER + "G90\nM83\nG28\nM104 S210\n")
    assert report.verdict is GCodeVerdict.BLOCKED
    assert any(i.code == "no_motion" for i in report.errors)


# --------------------------------------------------------------------------- #
# Unsupported Marlin commands
# --------------------------------------------------------------------------- #


def test_m413_is_reported_as_unsupported():
    report = analyse(good("M413 S1\n"))
    assert report.verdict is GCodeVerdict.WARNING
    assert any(u["command"] == "M413" for u in report.unsupported)
    issue = next(i for i in report.issues if i.code == "unsupported_command")
    assert "power-loss" in issue.detail.lower()


def test_g29_is_flagged_because_klipper_uses_bed_mesh_calibrate():
    report = analyse(good("G29\n"))
    assert any(u["command"] == "G29" for u in report.unsupported)


def test_each_unsupported_command_is_reported_once_not_per_line():
    report = analyse(good("M413 S1\n" * 50))
    assert len([i for i in report.issues if i.code == "unsupported_command"]) == 1


def test_supported_commands_are_not_flagged():
    report = analyse(good("M204 S2000\nM205 X8 Y8\nM220 S100\nM221 S95\nM486 S0\n"))
    assert report.unsupported == []


# --------------------------------------------------------------------------- #
# Motion limits versus the printer's approved profile
# --------------------------------------------------------------------------- #


def test_acceleration_above_the_printer_config_warns():
    report = analyse(good("M204 S9000\n"))
    assert report.max_requested_accel == 9000
    assert any(i.code == "accel_above_printer" for i in report.warnings)


def test_acceleration_within_the_printer_config_is_fine():
    report = analyse(good("M204 S2500\n"))
    assert not any(i.code == "accel_above_printer" for i in report.issues)


def test_set_velocity_limit_is_understood():
    report = analyse(good("SET_VELOCITY_LIMIT ACCEL=5000 VELOCITY=400\n"))
    assert report.max_requested_accel == 5000
    assert report.max_requested_feedrate == pytest.approx(400 * 60)
    assert any(i.code == "accel_above_printer" for i in report.warnings)
    assert any(i.code == "feedrate_above_printer" for i in report.warnings)


def test_feedrate_above_the_printer_config_warns():
    report = analyse(good("G1 X20 Y20 F30000\n"))
    assert any(i.code == "feedrate_above_printer" for i in report.warnings)


# --------------------------------------------------------------------------- #
# Slicer provenance
# --------------------------------------------------------------------------- #


def test_cura_output_is_marked_unverified():
    header = ";Generated with Cura_SteamEngine 5.6.0\n;Layer height: 0.2\n"
    report = analyse(good(header=header))
    assert report.slicer == "Cura"
    assert report.verified_profile is False
    assert report.profile_status == "unverified"
    issue = next(i for i in report.issues if i.code == "non_prusaslicer")
    assert "UNVERIFIED G-CODE" in issue.message


def test_an_unrecognised_slicer_is_marked_unverified():
    report = analyse(good(header="; some random exporter\n"))
    assert report.slicer == ""
    assert any(i.code == "unknown_slicer" for i in report.warnings)


def test_prusaslicer_with_a_non_golden_profile_warns():
    header = HEADER.replace("Neptune3Plus 0.20 Standard", "Experimental 0.28 Draft")
    report = analyse(good(header=header))
    assert report.profile_status == "known"
    assert report.verified_profile is False
    assert any(i.code == "unverified_profile" for i in report.warnings)


def test_provenance_alone_never_blocks_a_geometrically_valid_file():
    """Unverified is a warning, not a block - the user decides."""
    report = analyse(good(header=";Generated with Cura_SteamEngine 5.6.0\n"))
    assert report.verdict is GCodeVerdict.WARNING
    assert report.blocked is False


# --------------------------------------------------------------------------- #
# Nozzle
# --------------------------------------------------------------------------- #


def test_a_nozzle_mismatch_warns():
    header = HEADER.replace("nozzle_diameter = 0.4", "nozzle_diameter = 0.6")
    report = analyse(good(header=header))
    assert any(i.code == "nozzle_mismatch" for i in report.warnings)


# --------------------------------------------------------------------------- #
# Files
# --------------------------------------------------------------------------- #


def test_a_missing_file_is_an_error_not_a_crash(tmp_path):
    report = analyse_gcode_file(tmp_path / "nope.gcode", config=CONFIG)
    assert report.verdict is GCodeVerdict.BLOCKED
    assert any(i.code == "missing_file" for i in report.errors)


def test_a_real_file_round_trips(tmp_path):
    path = tmp_path / "cube.gcode"
    path.write_text(good(), encoding="utf-8")
    report = analyse_gcode_file(path, config=CONFIG, golden_profiles=GOLDEN)
    assert report.verdict is GCodeVerdict.SAFE


def test_binary_garbage_does_not_crash_the_analyser(tmp_path):
    path = tmp_path / "broken.gcode"
    path.write_bytes(b"\x00\x01\x02\xff\xfe not gcode at all")
    report = analyse_gcode_file(path, config=CONFIG)
    assert report.verdict is GCodeVerdict.BLOCKED


def test_the_report_serialises_for_the_api():
    payload = analyse(good()).as_dict()
    assert payload["verdict"] == "safe"
    assert payload["slicer"] == "PrusaSlicer"
    assert payload["bounds"]["max_x"] == 300.0
    assert payload["profile_status"] == "golden"


def test_a_foreign_file_cannot_claim_a_golden_profile_by_name():
    """A profile id is only a comment - trust needs the approved slicer too."""
    header = (
        ";Generated with Cura_SteamEngine 5.6.0\n"
        "; print_settings_id = Neptune3Plus 0.20 Standard\n"
    )
    report = analyse(good(header=header))
    assert report.verified_profile is False
    assert report.profile_status == "unverified"
    assert any(i.code == "non_prusaslicer" for i in report.warnings)
