"""End-to-end tests for the doctor / config / G-code endpoints.

These exercise the real FastAPI app with a mocked Moonraker, so they cover the
wiring as well as the logic.
"""

from __future__ import annotations

import json
from pathlib import Path

import httpx
import pytest
from fastapi.testclient import TestClient

from app.config import AppConfig
from app.main import create_app

PROFILES = Path(__file__).resolve().parent.parent / "profiles"

PRINTER_CFG = """
[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000

[stepper_x]
position_min: -3
position_max: 330

[stepper_y]
position_min: -8
position_max: 330

[stepper_z]
position_min: 0
position_max: 410

[probe]
z_offset: 2.15

[safe_z_home]
home_xy_position: 160, 160

[bed_mesh]
mesh_min: 30, 30

[screws_tilt_adjust]
screw1: 30, 30

[extruder]
nozzle_diameter: 0.4
min_extrude_temp: 170

#*# <---------------------- SAVE_CONFIG
#*# [probe]
#*# z_offset = 2.145
#*# [bed_mesh default]
#*# version = 1
"""

GCODE = """; generated by PrusaSlicer 2.8.1+linux
; nozzle_diameter = 0.4
; print_settings_id = Neptune3Plus 0.20 Standard
G90
M83
M104 S210
G28
G1 X10 Y10 Z0.2 F1800
G1 X300 Y300 E5 F3000
"""

#: Commands the fake Moonraker was asked to run.
SENT: list[str] = []
#: Advancing clock for the fake console buffer.
STORE_TICK = [0]


def moonraker_handler(request: httpx.Request) -> httpx.Response:
    path = request.url.path

    if path == "/server/info":
        return httpx.Response(200, json={"result": {"klippy_state": "ready", "klippy_connected": True}})
    if path == "/printer/info":
        return httpx.Response(200, json={"result": {"state": "ready", "state_message": "Ready"}})
    if path == "/printer/objects/list":
        return httpx.Response(200, json={"result": {"objects": ["toolhead", "extruder"]}})
    if path == "/printer/objects/query":
        return httpx.Response(
            200,
            json={
                "result": {
                    "status": {
                        "print_stats": {"state": "standby", "filename": ""},
                        "toolhead": {"homed_axes": "xyz", "position": [10, 10, 5, 0]},
                        "extruder": {"temperature": 24.0, "target": 0.0},
                        "heater_bed": {"temperature": 23.0, "target": 0.0},
                        "mcu": {"mcu_version": "v0.12.0", "last_stats": {"mcu_task_avg": 0.002}},
                    }
                }
            },
        )
    if path == "/server/files/config/printer.cfg":
        return httpx.Response(200, content=PRINTER_CFG.encode())
    if path.startswith("/server/files/logs/"):
        return httpx.Response(200, content=b"Starting Klippy...\n")
    if path == "/printer/gcode/script":
        SENT.append(request.url.params.get("script", ""))
        return httpx.Response(200, json={"result": "ok"})
    if path == "/server/gcode_store":
        # Moonraker's buffer grows as commands run; the client reads whatever
        # appeared after the marker it noted, so the timestamps must advance.
        STORE_TICK[0] += 1
        return httpx.Response(
            200,
            json={
                "result": {
                    "gcode_store": [
                        {"time": float(STORE_TICK[0]), "message": "// probe: open"}
                    ]
                }
            },
        )
    if path == "/printer/firmware_restart":
        return httpx.Response(200, json={"result": "ok"})
    if path.startswith("/server/files/gcodes/"):
        return httpx.Response(200, content=GCODE.encode())
    if path == "/server/files/upload":
        return httpx.Response(200, json={"result": {"item": {"path": "printer.cfg"}}})
    return httpx.Response(200, json={"result": {}})


@pytest.fixture()
def client(tmp_path: Path):
    SENT.clear()
    STORE_TICK[0] = 0
    config = AppConfig()
    config.paths.data_dir = str(tmp_path / "data")
    config.paths.models_dir = str(tmp_path / "data" / "models")
    config.paths.gcode_dir = str(tmp_path / "data" / "gcode")
    config.paths.database = str(tmp_path / "data" / "neptune.db")
    config.paths.profiles_dir = str(PROFILES)
    config.storage.root = str(tmp_path / "printer_data" / "neptune_remote")
    config.storage.backup_sources = []
    config.power.provider = "demo"
    config.camera.stream_url = ""
    config.camera.snapshot_url = ""
    config.camera.device = ""

    app = create_app(config)
    with TestClient(app) as test_client:
        services = app.state.services
        services.moonraker._client = httpx.AsyncClient(
            transport=httpx.MockTransport(moonraker_handler), base_url="http://moonraker"
        )
        yield test_client


# --------------------------------------------------------------------------- #
# Fix My Printer
# --------------------------------------------------------------------------- #


def test_diagnose_returns_cards_and_findings(client: TestClient):
    body = client.get("/api/doctor/diagnose").json()
    assert "overall" in body
    assert body["cards"]
    assert isinstance(body["findings"], list)
    assert "safe_to_print" in body


def test_health_endpoint_returns_one_card_per_subsystem(client: TestClient):
    body = client.get("/api/doctor/health").json()
    subsystems = {c["subsystem"] for c in body["cards"]}
    for required in ("klipper", "probe", "x_axis", "y_axis", "z_axis", "bed_mesh", "z_offset"):
        assert required in subsystems


def test_probe_query_reads_the_real_state(client: TestClient):
    body = client.post("/api/doctor/probe/query").json()
    assert body["known"] is True
    assert body["triggered"] is False
    assert "QUERY_PROBE" in SENT


# --------------------------------------------------------------------------- #
# Safe command execution
# --------------------------------------------------------------------------- #


def test_evaluating_a_command_sends_nothing(client: TestClient):
    body = client.post(
        "/api/doctor/command/evaluate", json={"command": "G1 X400 Y10"}
    ).json()
    assert body["kind"] == "movement"
    assert "X330" in body["command"]        # clamped to the live config
    assert SENT == []


def test_a_blocked_command_returns_409_and_is_never_sent(client: TestClient):
    client.post("/api/doctor/probe/query")
    SENT.clear()
    # TESTZ without a calibration session is blocked.
    response = client.post("/api/doctor/command/execute", json={"command": "TESTZ Z=-0.05"})
    assert response.status_code == 409
    detail = response.json()["detail"]
    assert detail["severity"] == "blocked"
    assert any(i["code"] == "no_calibration_session" for i in detail["issues"])
    assert SENT == []


def test_an_allowed_command_is_sent_after_clamping(client: TestClient):
    client.post("/api/doctor/probe/query")
    SENT.clear()
    body = client.post(
        "/api/doctor/command/execute", json={"command": "G1 X400 Y10", "force": True}
    ).json()
    assert body["allowed"] is True
    assert "X330" in SENT[-1]


def test_the_audit_log_records_decisions(client: TestClient):
    client.post("/api/doctor/probe/query")
    client.post("/api/doctor/command/execute", json={"command": "G1 X10", "force": True})
    entries = client.get("/api/doctor/command/audit").json()["entries"]
    assert any(e["original"] == "G1 X10" for e in entries)


# --------------------------------------------------------------------------- #
# Workflows
# --------------------------------------------------------------------------- #


def test_workflows_are_listed(client: TestClient):
    body = client.get("/api/doctor/workflows").json()
    kinds = {w["kind"] for w in body["available"]}
    assert {"z_offset", "screws_tilt", "bed_mesh", "full_bed_calibration", "axis_health"} <= kinds
    assert body["active"] is None


def test_a_workflow_runs_step_by_step(client: TestClient):
    started = client.post("/api/doctor/workflows/start", json={"kind": "safe_home"}).json()
    assert started["state"] == "running"
    assert started["steps"][0]["id"] == "probe_check"

    advanced = client.post("/api/doctor/workflows/advance?force=true").json()
    assert advanced["steps"][0]["state"] == "done"
    assert "QUERY_PROBE" in SENT


def test_two_workflows_cannot_run_at_once(client: TestClient):
    client.post("/api/doctor/workflows/start", json={"kind": "safe_home"})
    response = client.post("/api/doctor/workflows/start", json={"kind": "bed_mesh"})
    assert response.status_code == 409


def test_cancelling_frees_the_runner(client: TestClient):
    client.post("/api/doctor/workflows/start", json={"kind": "safe_home"})
    client.post("/api/doctor/workflows/cancel")
    assert client.post("/api/doctor/workflows/start", json={"kind": "bed_mesh"}).status_code == 200


def test_an_unknown_workflow_is_404(client: TestClient):
    assert client.post("/api/doctor/workflows/start", json={"kind": "nope"}).status_code == 404


def test_testz_outside_a_session_is_refused_by_the_api(client: TestClient):
    response = client.post("/api/doctor/calibrate/testz", json={"delta": -0.05})
    assert response.status_code == 409


# --------------------------------------------------------------------------- #
# Config versions
# --------------------------------------------------------------------------- #


def test_the_live_config_is_read_and_validated(client: TestClient):
    body = client.get("/api/config/live").json()
    assert "[printer]" in body["text"]
    assert "printer" in body["sections"]
    assert body["validation"]["verdict"] in {"ok", "warning"}
    assert len(body["sha256"]) == 64


def test_reading_the_live_config_records_a_first_version(client: TestClient):
    client.get("/api/config/live")
    versions = client.get("/api/config/versions").json()["versions"]
    assert versions
    assert versions[-1]["reason"] == "imported"


def test_a_version_can_be_named_and_marked_golden(client: TestClient):
    client.get("/api/config/live")
    version_id = client.get("/api/config/versions").json()["versions"][0]["id"]

    client.post(f"/api/config/versions/{version_id}/label", json={"label": "Before ADXL"})
    marked = client.post(f"/api/config/versions/{version_id}/golden").json()
    assert marked["golden"] is True

    listing = client.get("/api/config/versions").json()
    assert listing["golden"]["id"] == version_id


def test_a_golden_version_cannot_be_deleted(client: TestClient):
    client.get("/api/config/live")
    version_id = client.get("/api/config/versions").json()["versions"][0]["id"]
    client.post(f"/api/config/versions/{version_id}/golden")
    response = client.delete(f"/api/config/versions/{version_id}")
    assert response.status_code == 409


def test_restore_requires_confirmation_first(client: TestClient):
    client.get("/api/config/live")
    version_id = client.get("/api/config/versions").json()["versions"][0]["id"]
    client.post(f"/api/config/versions/{version_id}/golden")

    body = client.post("/api/config/restore", json={"version_id": version_id}).json()
    assert body["requires_confirmation"] is True
    assert "diff" in body


def test_restore_without_a_known_good_version_is_404(client: TestClient):
    assert client.post("/api/config/restore", json={"confirm": True}).status_code == 404


# --------------------------------------------------------------------------- #
# G-code inspector and preflight
# --------------------------------------------------------------------------- #


def test_the_inspector_reports_bounds_and_provenance(client: TestClient):
    body = client.get("/api/gcode/inspect", params={"filename": "cube.gcode"}).json()
    assert body["slicer"] == "PrusaSlicer"
    assert body["bounds"]["max_x"] == 300.0
    assert body["verdict"] in {"safe", "warning"}


def test_preflight_produces_the_pre_print_banner(client: TestClient):
    body = client.get("/api/gcode/preflight", params={"filename": "cube.gcode"}).json()
    banner = body["banner"]
    assert banner["slicer"] == "PrusaSlicer"
    assert banner["build_volume"] == "PASSED"
    assert banner["unsupported_commands"] == "NONE"
    assert body["verdict"] in {"ready", "warning"}


def test_strict_mode_is_stricter(client: TestClient):
    lenient = client.get("/api/gcode/preflight", params={"filename": "cube.gcode"}).json()
    strict = client.get(
        "/api/gcode/preflight", params={"filename": "cube.gcode", "strict": "true"}
    ).json()
    assert strict["strict"] is True
    # Strict can only ever be the same or worse.
    order = {"ready": 0, "warning": 1, "blocked": 2}
    assert order[strict["verdict"]] >= order[lenient["verdict"]]


# --------------------------------------------------------------------------- #
# Golden slicer profiles
# --------------------------------------------------------------------------- #


def test_a_slicer_profile_can_be_saved_and_pinned(client: TestClient):
    created = client.post(
        "/api/slicer/profiles",
        json={"name": "Neptune3Plus 0.20 Standard", "settings": {"layer_height": 0.2}},
    ).json()
    assert created["version"] == 1
    assert created["status"] == "candidate"

    pinned = client.post(f"/api/slicer/profiles/{created['id']}/golden").json()
    assert pinned["golden"] is True

    listing = client.get("/api/slicer/profiles").json()
    assert "Neptune3Plus 0.20 Standard" in listing["golden_names"]


def test_editing_a_golden_profile_creates_a_new_version(client: TestClient):
    created = client.post(
        "/api/slicer/profiles", json={"name": "P", "settings": {"accel": 3000}}
    ).json()
    client.post(f"/api/slicer/profiles/{created['id']}/golden")

    edited = client.post(
        "/api/slicer/profiles", json={"name": "P", "settings": {"accel": 6000}}
    ).json()
    assert edited["id"] != created["id"]
    assert edited["version"] == 2
    assert edited["golden"] is False


def test_a_golden_profile_cannot_be_deleted_through_the_api(client: TestClient):
    created = client.post("/api/slicer/profiles", json={"name": "P", "settings": {}}).json()
    client.post(f"/api/slicer/profiles/{created['id']}/golden")
    assert client.delete(f"/api/slicer/profiles/{created['id']}").status_code == 409


def test_a_golden_profile_makes_matching_gcode_verified(client: TestClient):
    created = client.post(
        "/api/slicer/profiles",
        json={"name": "Neptune3Plus 0.20 Standard", "settings": {}},
    ).json()
    client.post(f"/api/slicer/profiles/{created['id']}/golden")

    body = client.get("/api/gcode/inspect", params={"filename": "cube.gcode"}).json()
    assert body["profile_status"] == "golden"
    assert body["verified_profile"] is True
