"""Carrying on from a layer, and printing only part of a file."""

from __future__ import annotations

from pathlib import Path

import pytest

from app.gcode.preview import build_index
from app.gcode.resume import (
    DEFAULT_PRIME_MM,
    MachineState,
    ResumeError,
    assess,
    build_preamble,
    build_resumed_file,
    state_at_layer,
)

SLICED = """\
; generated by PrusaSlicer
M140 S60
M190 S60
M104 S215
M109 S215
G90
M83
G28
G1 Z0.2 F600
;LAYER_CHANGE
;Z:0.2
;TYPE:External perimeter
M106 S102
G1 X10 Y10 F9000
G1 X40 Y10 E1.0
;LAYER_CHANGE
;Z:0.4
;TYPE:Perimeter
M106 S255
G1 X40 Y30 E1.0 F1800
;LAYER_CHANGE
;Z:0.6
;TYPE:Perimeter
G1 X10 Y30 E1.0
;LAYER_CHANGE
;Z:0.8
;TYPE:Perimeter
G1 X10 Y10 E1.0
M104 S0
M140 S0
M107
G28 X Y
M84
"""


def sliced(tmp_path: Path, text: str = SLICED, name: str = "part.gcode") -> Path:
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


def index_for(path: Path):
    return build_index(path)


def safe_state(path: Path, layer: int = 2):
    index = index_for(path)
    state = state_at_layer(path, index, layer)
    # Homing point far from the 10..40 part, so Z can be measured.
    safety = assess(
        index, z_home_point=(160.0, 160.0), force_move_enabled=False, state=state
    )
    return index, state, safety


# --------------------------------------------------------------------------- #
# Reading the state
# --------------------------------------------------------------------------- #


def test_the_temperatures_in_force_at_a_layer_are_recovered(tmp_path: Path):
    path = sliced(tmp_path)
    state = state_at_layer(path, index_for(path), 2)

    assert state.nozzle_temp == pytest.approx(215.0)
    assert state.bed_temp == pytest.approx(60.0)


def test_a_cooldown_after_the_layer_does_not_leak_backwards(tmp_path: Path):
    # The file ends with M104 S0. Resuming at layer 3 must not resume at zero.
    path = sliced(tmp_path)
    state = state_at_layer(path, index_for(path), 3)

    assert state.nozzle_temp == pytest.approx(215.0)


def test_the_fan_speed_is_the_last_one_set_before_the_layer(tmp_path: Path):
    path = sliced(tmp_path)

    assert state_at_layer(path, index_for(path), 1).fan_speed == pytest.approx(102.0)
    # M106 S255 runs inside layer 1, so by layer 2 it is in force.
    assert state_at_layer(path, index_for(path), 2).fan_speed == pytest.approx(255.0)
    assert state_at_layer(path, index_for(path), 2).fan_percent == pytest.approx(100.0)


def test_the_extrusion_mode_the_file_was_using_is_carried_over(tmp_path: Path):
    # M83 in the header: relative extrusion. Resuming in absolute mode would
    # make the first move extrude the whole print's filament at once.
    path = sliced(tmp_path)
    state = state_at_layer(path, index_for(path), 2)

    assert state.absolute_extrusion is False
    assert state.absolute_positioning is True


def test_the_layers_own_z_wins_over_the_last_z_move(tmp_path: Path):
    # A Z-hop before the layer would otherwise be mistaken for the layer height.
    path = sliced(tmp_path)

    assert state_at_layer(path, index_for(path), 2).z == pytest.approx(0.6)


def test_the_feedrate_in_force_is_remembered(tmp_path: Path):
    path = sliced(tmp_path)
    assert state_at_layer(path, index_for(path), 2).feedrate == pytest.approx(1800.0)


def test_asking_about_a_layer_that_is_not_there_is_refused(tmp_path: Path):
    path = sliced(tmp_path)
    with pytest.raises(ResumeError):
        state_at_layer(path, index_for(path), 99)


# --------------------------------------------------------------------------- #
# Safety
# --------------------------------------------------------------------------- #


def test_a_homing_point_clear_of_the_part_allows_z_to_be_measured(tmp_path: Path):
    _, _, safety = safe_state(sliced(tmp_path))

    assert safety.can_home_z is True
    assert safety.is_safe


def test_a_homing_point_inside_the_part_refuses_to_home_z(tmp_path: Path):
    path = sliced(tmp_path)
    index = index_for(path)
    state = state_at_layer(path, index, 2)

    # The part spans 10..40. Homing at its centre would drive the nozzle into
    # it - which is a nozzle through a print and possibly through a bed.
    safety = assess(
        index, z_home_point=(25.0, 20.0), force_move_enabled=True, state=state
    )

    assert safety.can_home_z is False
    assert safety.is_safe                      # force_move gives it another way
    assert any("جوه مساحة القطعة" in warning for warning in safety.warnings_ar)


def test_without_force_move_an_unhomeable_z_is_a_blocker(tmp_path: Path):
    path = sliced(tmp_path)
    index = index_for(path)
    state = state_at_layer(path, index, 2)

    safety = assess(
        index, z_home_point=(25.0, 20.0), force_move_enabled=False, state=state
    )

    assert not safety.is_safe
    assert any("force_move" in blocker for blocker in safety.blockers_ar)


def test_an_unknown_homing_point_is_warned_about(tmp_path: Path):
    path = sliced(tmp_path)
    index = index_for(path)
    state = state_at_layer(path, index, 2)

    safety = assess(
        index, z_home_point=None, force_move_enabled=True, state=state
    )

    assert safety.can_home_z is False
    assert any("safe_z_home" in warning for warning in safety.warnings_ar)


def test_a_layer_with_no_recorded_height_cannot_be_resumed(tmp_path: Path):
    # Without a Z there is nowhere to resume to, and guessing is a crash.
    path = sliced(tmp_path, "G90\n;LAYER:0\nG1 X10 Y10 E1\n", name="cura.gcode")
    index = index_for(path)
    state = state_at_layer(path, index, 0)

    safety = assess(
        index, z_home_point=(160.0, 160.0), force_move_enabled=True, state=state
    )

    assert not safety.is_safe


# --------------------------------------------------------------------------- #
# The preamble
# --------------------------------------------------------------------------- #


def test_the_bed_is_heated_and_waited_for_before_anything_moves(tmp_path: Path):
    _, state, safety = safe_state(sliced(tmp_path))
    lines = build_preamble(state, safety, layer=2)

    wait = next(i for i, line in enumerate(lines) if line.startswith("M190"))
    home = next(i for i, line in enumerate(lines) if line.startswith("G28"))

    # A cold sheet is a different size from a hot one: the part moves as it
    # warms, and resuming before it has finished lands the layer beside it.
    assert wait < home


def test_only_x_and_y_are_homed(tmp_path: Path):
    _, state, safety = safe_state(sliced(tmp_path))
    lines = build_preamble(state, safety, layer=2)

    homing = [line for line in lines if line.startswith("G28")]
    assert homing == ["G28 X Y"] or homing == ["G28 X Y", "G28 Z"]
    assert "G28" not in homing            # never a bare home-everything


def test_z_is_asserted_when_it_cannot_be_measured(tmp_path: Path):
    path = sliced(tmp_path)
    index = index_for(path)
    state = state_at_layer(path, index, 2)
    safety = assess(index, z_home_point=(25.0, 20.0), force_move_enabled=True, state=state)

    lines = build_preamble(state, safety, layer=2)

    assert any(line.startswith("SET_KINEMATIC_POSITION") for line in lines)
    assert not any(line.strip() == "G28 Z" for line in lines)


def test_the_toolhead_lifts_before_it_travels(tmp_path: Path):
    _, state, safety = safe_state(sliced(tmp_path))
    lines = build_preamble(state, safety, layer=2)

    moves = [line for line in lines if line.startswith("G1 ")]
    lift = next(i for i, line in enumerate(moves) if line.startswith("G1 Z"))
    travel = next((i for i, line in enumerate(moves) if line.startswith("G1 X")), None)

    # Travelling at layer height drags the nozzle across everything printed.
    assert travel is None or lift < travel


def test_the_nozzle_is_primed_after_a_long_wait(tmp_path: Path):
    _, state, safety = safe_state(sliced(tmp_path))
    lines = build_preamble(state, safety, layer=2)

    assert any(f"E{DEFAULT_PRIME_MM:.2f}" in line for line in lines)


def test_priming_can_be_turned_off(tmp_path: Path):
    _, state, safety = safe_state(sliced(tmp_path))
    lines = build_preamble(state, safety, layer=2, prime_mm=0)

    assert not any("G1 E" in line for line in lines)


def test_the_extrusion_mode_is_restored_last(tmp_path: Path):
    # The prime uses M83 regardless; the file's own mode has to be put back
    # after it or every following E value means something different.
    _, state, safety = safe_state(sliced(tmp_path))
    lines = build_preamble(state, safety, layer=2)

    prime = max(i for i, line in enumerate(lines) if line.startswith("G1 E"))
    restore = max(i for i, line in enumerate(lines) if line in ("M82", "M83"))

    assert restore > prime
    assert lines[restore] == "M83"          # the fixture prints in relative mode


def test_a_changed_filament_can_be_printed_hotter(tmp_path: Path):
    # Resuming with a different spool is the common case, and the new material
    # may not run at the old temperature.
    _, state, safety = safe_state(sliced(tmp_path))
    lines = build_preamble(state, safety, layer=2, nozzle_temp=240, bed_temp=80)

    assert "M109 S240" in lines
    assert "M190 S80" in lines


# --------------------------------------------------------------------------- #
# Writing the file
# --------------------------------------------------------------------------- #


def test_a_resumed_file_starts_at_the_chosen_layer(tmp_path: Path):
    path = sliced(tmp_path)
    index, state, safety = safe_state(path)

    out = build_resumed_file(
        path, tmp_path / "resumed.gcode", index,
        start_layer=2, safety=safety, state=state,
    )
    text = out.read_text(encoding="utf-8")

    assert "resumed at layer 3" in text
    # Layer 0 and 1 geometry is gone; layer 2 onwards is present.
    assert "X40 Y10 E1.0" not in text
    assert "X10 Y30 E1.0" in text


def test_a_resume_keeps_the_slicers_own_ending(tmp_path: Path):
    path = sliced(tmp_path)
    index, state, safety = safe_state(path)

    out = build_resumed_file(
        path, tmp_path / "resumed.gcode", index,
        start_layer=2, safety=safety, state=state,
    )
    text = out.read_text(encoding="utf-8")

    # Turning the heaters off and parking is the slicer's job, and it lives at
    # the end of the file we kept.
    assert "M84" in text


def test_a_range_stops_after_the_end_layer(tmp_path: Path):
    path = sliced(tmp_path)
    index, state, safety = safe_state(path)

    out = build_resumed_file(
        path, tmp_path / "piece.gcode", index,
        start_layer=1, end_layer=2, safety=safety, state=state,
    )
    text = out.read_text(encoding="utf-8")

    assert "X40 Y30 E1.0" in text          # layer 1
    assert "X10 Y30 E1.0" in text          # layer 2
    assert "X10 Y10 E1.0" not in text      # layer 3 is past the end


def test_a_range_gets_its_own_ending_since_the_slicers_never_runs(tmp_path: Path):
    path = sliced(tmp_path)
    index, state, safety = safe_state(path)

    out = build_resumed_file(
        path, tmp_path / "piece.gcode", index,
        start_layer=1, end_layer=2, safety=safety, state=state,
    )
    text = out.read_text(encoding="utf-8")

    assert "end of the requested range" in text
    assert "M104 S0" in text
    assert "M140 S0" in text


def test_an_end_before_the_start_is_refused(tmp_path: Path):
    path = sliced(tmp_path)
    index, state, safety = safe_state(path)

    with pytest.raises(ResumeError):
        build_resumed_file(
            path, tmp_path / "x.gcode", index,
            start_layer=3, end_layer=1, safety=safety, state=state,
        )


def test_a_blocked_safety_check_refuses_to_write_anything(tmp_path: Path):
    path = sliced(tmp_path)
    index = index_for(path)
    state = state_at_layer(path, index, 2)
    safety = assess(index, z_home_point=(25.0, 20.0), force_move_enabled=False, state=state)
    target = tmp_path / "never.gcode"

    with pytest.raises(ResumeError):
        build_resumed_file(
            path, target, index, start_layer=2, safety=safety, state=state,
        )

    assert not target.exists()


def test_no_half_written_file_is_left_behind_on_failure(tmp_path: Path):
    path = sliced(tmp_path)
    index, state, safety = safe_state(path)
    target = tmp_path / "out.gcode"

    with pytest.raises(ResumeError):
        build_resumed_file(
            path, target, index, start_layer=99, safety=safety, state=state,
        )

    assert not target.exists()
    assert not target.with_suffix(".gcode.partial").exists()


def test_the_source_file_is_never_modified(tmp_path: Path):
    path = sliced(tmp_path)
    before = path.read_bytes()
    index, state, safety = safe_state(path)

    build_resumed_file(
        path, tmp_path / "resumed.gcode", index,
        start_layer=2, safety=safety, state=state,
    )

    assert path.read_bytes() == before
