"""Extract statistics from a sliced G-code file.

PrusaSlicer, SuperSlicer and OrcaSlicer all append a comment block at the end of
the file. We read the head and the tail of the file only, so multi-hundred-MB
G-code stays cheap to inspect.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, Optional

HEAD_BYTES = 96 * 1024
TAIL_BYTES = 96 * 1024

_TIME_TOKEN = re.compile(r"(\d+)\s*([dhms])")

PATTERNS: Dict[str, list[re.Pattern[str]]] = {
    "estimated_time": [
        re.compile(r";\s*estimated printing time \(normal mode\)\s*=\s*(.+)", re.I),
        re.compile(r";\s*estimated printing time\s*=\s*(.+)", re.I),
        re.compile(r";\s*model printing time:\s*(.+?);", re.I),  # OrcaSlicer
        re.compile(r";TIME:\s*(\d+)", re.I),  # Cura
    ],
    "filament_grams": [
        re.compile(r";\s*total filament used \[g\]\s*=\s*([\d.]+)", re.I),
        re.compile(r";\s*filament used \[g\]\s*=\s*([\d.]+)", re.I),
        re.compile(r";\s*total filament weight \[g\]\s*:\s*([\d.]+)", re.I),
    ],
    "filament_mm": [
        re.compile(r";\s*filament used \[mm\]\s*=\s*([\d.]+)", re.I),
        re.compile(r";\s*total filament length \[mm\]\s*:\s*([\d.]+)", re.I),
        re.compile(r";Filament used:\s*([\d.]+)m", re.I),
    ],
    "filament_cm3": [
        re.compile(r";\s*filament used \[cm3\]\s*=\s*([\d.]+)", re.I),
    ],
    "layer_count": [
        re.compile(r";\s*total layers? count\s*=\s*(\d+)", re.I),
        re.compile(r";\s*total layer number:\s*(\d+)", re.I),
        re.compile(r";LAYER_COUNT:\s*(\d+)", re.I),
    ],
    "layer_height": [
        re.compile(r";\s*layer_height\s*=\s*([\d.]+)", re.I),
        re.compile(r";\s*layer height:\s*([\d.]+)", re.I),
    ],
    "object_height": [
        re.compile(r";\s*max_print_height\s*=\s*([\d.]+)", re.I),
        re.compile(r";\s*object height:\s*([\d.]+)", re.I),
    ],
    "filament_type": [
        re.compile(r";\s*filament_type\s*=\s*(\S+)", re.I),
    ],
    "slicer": [
        re.compile(r";\s*generated by\s+(.+)", re.I),
    ],
}


def parse_duration(text: str) -> Optional[float]:
    """Parse '2h 13m 5s', '1d 4h', or a bare number of seconds."""
    text = text.strip()
    if not text:
        return None
    if text.replace(".", "", 1).isdigit():
        return float(text)
    total = 0.0
    found = False
    for value, unit in _TIME_TOKEN.findall(text.lower()):
        found = True
        seconds = {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
        total += float(value) * seconds
    return total if found else None


def _read_edges(path: Path) -> str:
    size = path.stat().st_size
    with path.open("rb") as handle:
        head = handle.read(min(HEAD_BYTES, size))
        if size > HEAD_BYTES + TAIL_BYTES:
            handle.seek(-TAIL_BYTES, 2)
            tail = handle.read(TAIL_BYTES)
        else:
            tail = b""
    return (head + b"\n" + tail).decode("utf-8", errors="replace")


def count_layer_changes(path: Path) -> Optional[int]:
    """Fallback layer count: number of ``;LAYER_CHANGE`` / ``;LAYER:`` markers."""
    try:
        count = 0
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            for line in handle:
                if line.startswith(";LAYER_CHANGE") or line.startswith(";LAYER:"):
                    count += 1
        return count or None
    except OSError:
        return None


def parse_gcode(path: Path) -> Dict[str, Optional[float | int | str]]:
    path = Path(path)
    if not path.is_file():
        return {}

    text = _read_edges(path)
    result: Dict[str, Optional[float | int | str]] = {}

    for key, patterns in PATTERNS.items():
        for pattern in patterns:
            match = pattern.search(text)
            if not match:
                continue
            raw = match.group(1).strip()
            if key == "estimated_time":
                result[key] = parse_duration(raw)
            elif key in {"filament_type", "slicer"}:
                result[key] = raw
            elif key == "layer_count":
                result[key] = int(float(raw))
            else:
                try:
                    result[key] = float(raw)
                except ValueError:
                    result[key] = None
            if result.get(key) is not None:
                break

    # Cura reports filament in metres.
    if result.get("filament_mm") is not None and ";Filament used:" in text:
        value = result["filament_mm"]
        if isinstance(value, float) and value < 100:
            result["filament_mm"] = value * 1000.0

    if result.get("layer_count") is None:
        result["layer_count"] = count_layer_changes(path)

    result["gcode_size"] = path.stat().st_size
    return result


def color_changes(path: Path) -> list:
    """The filament swaps a G-code file will stop for.

    Read from the file's own header rather than from the slice job, so a file
    sliced last week - or uploaded from somewhere else entirely - still says
    what it is going to ask for.
    """
    path = Path(path)
    if not path.is_file():
        return []
    from .colors import parse_manifest

    try:
        return parse_manifest(_read_edges(path))
    except OSError:
        return []
