/**
 * reportGenerator.ts — assembles a professional pentest-style Markdown report
 * from structured findings. Pure formatting; no external calls.
 */

import type { Severity } from "./codeReview";

export interface ReportFinding {
  title: string;
  severity: Severity;
  description: string;
  impact?: string;
  remediation?: string;
  evidence?: string;
}

export interface ReportInput {
  title?: string;
  client?: string;
  author?: string;
  scope?: string[];
  methodology?: string[];
  findings: ReportFinding[];
  recommendations?: string[];
}

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low", "info"];

function severityBadge(sev: Severity): string {
  const map: Record<Severity, string> = {
    critical: "CRITICAL",
    high: "HIGH",
    medium: "MEDIUM",
    low: "LOW",
    info: "INFO",
  };
  return map[sev];
}

export function generateReport(input: ReportInput): string {
  const {
    title = "Security Assessment Report",
    client = "Internal / Lab Engagement",
    author = "Horus Cyber Agent",
    scope = [],
    methodology = [
      "Reconnaissance and scope confirmation (owned/lab assets only)",
      "OWASP Top 10 oriented review",
      "Secure code review of provided sources",
      "Defensive log analysis",
      "Findings triage and remediation guidance",
    ],
    findings,
    recommendations = [],
  } = input;

  const date = new Date().toISOString().slice(0, 10);

  const sorted = [...findings].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );

  const counts: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
  };
  for (const f of findings) counts[f.severity]++;

  const summaryTable =
    `| Severity | Count |\n|----------|-------|\n` +
    SEVERITY_ORDER.map((s) => `| ${severityBadge(s)} | ${counts[s]} |`).join("\n");

  const findingsMd = sorted
    .map((f, i) => {
      return `### ${i + 1}. ${f.title}  \n**Severity:** ${severityBadge(
        f.severity
      )}\n\n**Description**  \n${f.description}\n\n**Evidence**  \n${
        f.evidence ?? "_[Attach screenshots / request-response samples here]_"
      }\n\n**Impact**  \n${f.impact ?? "_Describe the business/technical impact._"}\n\n**Remediation**  \n${
        f.remediation ?? "_Provide concrete remediation steps._"
      }`;
    })
    .join("\n\n---\n\n");

  const scopeMd =
    scope.length > 0
      ? scope.map((s) => `- ${s}`).join("\n")
      : "- _[List the in-scope, owned/authorized assets here]_";

  const methodologyMd = methodology.map((m) => `- ${m}`).join("\n");

  const recommendationsMd =
    recommendations.length > 0
      ? recommendations.map((r) => `- ${r}`).join("\n")
      : "- Remediate Critical/High findings first.\n- Add the recommended security headers and dependency scanning.\n- Re-test after fixes and integrate checks into CI.";

  return `# ${title}

**Client / Engagement:** ${client}
**Prepared by:** ${author}
**Date:** ${date}

> Authorization: this assessment covers only assets the engagement owner has
> confirmed they own or are explicitly authorized to test.

## 1. Executive Summary

This report summarizes the results of a security assessment performed on the
in-scope assets. A total of **${findings.length}** finding(s) were identified.

${summaryTable}

## 2. Scope

${scopeMd}

## 3. Methodology

${methodologyMd}

## 4. Findings

${findings.length > 0 ? findingsMd : "_No findings recorded yet._"}

## 5. Final Recommendations

${recommendationsMd}

---
_Generated by Horus Cyber Agent — safe, ethical security tooling._
`;
}
