# name: ABS
# description: ABS. Almost no part cooling to avoid warping and layer splitting.

filament_type = ABS
filament_settings_id = ABS
filament_notes = Tuned for the Elegoo Neptune 3 Plus. Adjust freely.

temperature = 245
first_layer_temperature = 250
bed_temperature = 100
first_layer_bed_temperature = 100

fan_always_on = 1
min_fan_speed = 0
max_fan_speed = 15
bridge_fan_speed = 15
disable_fan_first_layers = 1
cooling = 1
slowdown_below_layer_time = 8
min_print_speed = 12
fan_below_layer_time = 30

filament_max_volumetric_speed = 11
filament_density = 1.04
filament_diameter = 1.75
extrusion_multiplier = 1
filament_cost = 0

filament_retract_length = 1
filament_retract_speed = nil
filament_retract_lift = nil
