# name: PETG
# description: PETG. Lower fan, longer retraction to fight stringing.

filament_type = PETG
filament_settings_id = PETG
filament_notes = Tuned for the Elegoo Neptune 3 Plus. Adjust freely.

temperature = 235
first_layer_temperature = 240
bed_temperature = 75
first_layer_bed_temperature = 80

fan_always_on = 1
min_fan_speed = 40
max_fan_speed = 60
bridge_fan_speed = 60
disable_fan_first_layers = 1
cooling = 1
slowdown_below_layer_time = 8
min_print_speed = 12
fan_below_layer_time = 30

filament_max_volumetric_speed = 8
filament_density = 1.27
filament_diameter = 1.75
extrusion_multiplier = 1
filament_cost = 0

filament_retract_length = 1.4
filament_retract_speed = nil
filament_retract_lift = nil
