# name: Klipper Fast
# description: Aggressive Klipper speeds. Requires input shaper and pressure advance to be tuned.

layer_height = 0.24
first_layer_height = 0.28

perimeters = 2
top_solid_layers = 5
bottom_solid_layers = 4
top_solid_min_thickness = 0.7
bottom_solid_min_thickness = 0.5
extra_perimeters = 0
ensure_vertical_shell_thickness = 1
thin_walls = 0
seam_position = aligned

fill_density = 15%
fill_pattern = grid
top_fill_pattern = monotonic
bottom_fill_pattern = monotonic
infill_every_layers = 1
solid_infill_every_layers = 0
fill_angle = 45

# ---- speeds (mm/s) --------------------------------------------------------
perimeter_speed = 150
external_perimeter_speed = 70
small_perimeter_speed = 70
infill_speed = 250
solid_infill_speed = 200
top_solid_infill_speed = 70
gap_fill_speed = 70
support_material_speed = 250
bridge_speed = 25
first_layer_speed = 30
travel_speed = 400
max_print_speed = 250
max_volumetric_speed = 0

# ---- acceleration ---------------------------------------------------------
default_acceleration = 8000
perimeter_acceleration = 8000
external_perimeter_acceleration = 8000
infill_acceleration = 8000
solid_infill_acceleration = 8000
top_solid_infill_acceleration = 8000
bridge_acceleration = 8000
first_layer_acceleration = 1000
travel_acceleration = 8000

# ---- supports & adhesion --------------------------------------------------
support_material = 0
support_material_auto = 1
support_material_style = grid
support_material_threshold = 55
support_material_contact_distance = 0.2
support_material_spacing = 2.5
support_material_buildplate_only = 0
skirts = 2
skirt_distance = 3
skirt_height = 1
brim_width = 0
brim_type = outer_only
raft_layers = 0

# ---- misc -----------------------------------------------------------------
elefant_foot_compensation = 0.15
xy_size_compensation = 0
gcode_comments = 0
gcode_label_objects = 1
complete_objects = 0
